services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
      interval: 5s
      timeout: 5s
      retries: 10

  airflow:
    image: apache/airflow:2.9.3-python3.10
    container_name: airflow
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: America/New_York
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      PYTHONPATH: /workspace
      PIP_USER: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ../:/workspace
    command: >
      bash -lc "\ pip install --no-cache-dir -r /opt/airflow/requirements.txt && \ airflow db migrate && \ airflow users create \ --username ${_AIRFLOW_WWW_USER_USERNAME} \ --password ${_AIRFLOW_WWW_USER_PASSWORD} \ --firstname Admin --lastname User \ --role Admin --email admin@example.com || true && \ airflow webserver --port 8080 & \ exec airflow scheduler"
    restart: unless-stopped
