name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  test-and-build:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          [ -f services/api/requirements.txt ] && pip install -r services/api/requirements.txt || true

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -m pytest -q

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & (on push) push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/api/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/hyachinth/bluebikes-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
